### ISSUE TITLE
VR compability ?

### ISSUE THREAD

**Issue by Shirouste** [ManlyMarco/IllusionCheatTools#16]
Is it possible to make this tool available for VR ? I tried with Koikatsu, cheat is available in normal mode, but not when I launch the VR exe. I would like to unlock all positions but it doesn't reflect when using VR

**Comment by ManlyMarco** [comment]
If you unlock in main game then it should get saved and carry over to the VR module I believe.

At the moment I don't have a VR headset so I can't do anything about it.

**Comment by ManlyMarco** [comment]
I looked into it, and you can use it in VR but it will only appear in game window, not in the headset. 

It seems like all poses were unlocked after running the unlock all poses command in normal game and quitting. Can you test if this build unlocks the positions correctly? [build.zip](https://github.com/ManlyMarco/IllusionCheatTools/files/5164340/build.zip)

**Comment by ManlyMarco** [comment]
Closing stale issue. The display issue is something to be fixed in a separate plugin.
