### ISSUE TITLE
letters are missing

### ISSUE THREAD

**Issue by 7462432** [ManlyMarco/IllusionCheatTools#20]
I can open the Tool but I don't have any letters. ( I'm using a Mac with CrossOver and RX17.)
Is there any way to fix it?
<img width="689" alt="1" src="https://user-images.githubusercontent.com/129138892/228924917-1385e849-dda5-45c4-ac33-9f0dc4bd7dc3.png">

**Comment by ManlyMarco** [comment]
This isn't CheatTools. Look into the game log and resolve any warnings or errors at startup.

**Comment by 7462432** [comment]
Is that cheat tools? I can't see it because of the missing letters. I can operate the different windows and move the sliders but I can't see any letters. The same problem occurs with in card selection. I can't see anything in the logs that indicates a cause.
<img width="1728" alt="1" src="https://user-images.githubusercontent.com/129138892/228965121-a560ffe4-523f-498a-98a9-18f0a0fd5caf.png">

**Comment by ManlyMarco** [comment]
Can you try that game install on a Windows or Linux system to see if the issue is related to the OS? You can also try making a clean install of the game. You can also ask in the #help channel on the discord server and send your game log there, maybe there are hints in there.

**Comment by ManlyMarco** [comment]
Closing as stale.
