### ISSUE TITLE
The wall piercing feature of AI girl's CheatTools has been ineffective since the previous versions

### ISSUE THREAD

**Issue by XHxiaohuaXH** [ManlyMarco/IllusionCheatTools#22]
The wall piercing feature of AI girl's CheatTools has been ineffective since the previous versions

**Comment by ManlyMarco** [comment]
What exactly is the issue? Which version exactly did it stop working on?

**Comment by XHxiaohuaXH** [comment]
I don't remember from which version the noclip feature has stopped working，I have updated the version several times, but it still hasn't been fixed

**Comment by XHxiaohuaXH** [comment]
I don't remember from which version the "Enable player noclip" feature has stopped working，I have updated the version several times, but it still hasn't been fixed
