### ISSUE TITLE
The“Enable player noclip”function of AI_CheatTools 3.3.1 still cannot be used

### ISSUE THREAD

**Issue by XHxiaohuaXH** [ManlyMarco/IllusionCheatTools#25]
![QQ图片20240417003506](https://github.com/ManlyMarco/IllusionCheatTools/assets/134010022/05ad5e81-6c35-4681-8a43-b984f6cf39fd)

**Enable, players cannot walk on the road**

**Comment by ManlyMarco** [comment]
You're right, it got broken a few versions back.

**Comment by ManlyMarco** [comment]
Here's a fixed build, it might take some time until the next release. 
[AI_CheatTools.zip](https://github.com/ManlyMarco/IllusionCheatTools/files/15002053/AI_CheatTools.zip)
