### ISSUE TITLE
AI CheatTools cannot edit Flavor skills

### ISSUE THREAD

**Issue by EnchantShiroe** [ManlyMarco/IllusionCheatTools#28]
Cannot delete, change
![Screenshot 2024-07-17 031001](https://github.com/user-attachments/assets/8dd985b4-4e16-4879-9be5-3303ddd9f1d4)
![image](https://github.com/user-attachments/assets/b5ddc579-6f2e-4509-b851-6b45e6d333cd)

**Comment by ManlyMarco** [comment]
What is the issue exactly? What do you expect to be happening and what is actually happening?
